az-configuration:
- name: az1
  iaas_configuration_name: default
  clusters:
  - cluster: ((vsphere_cluster))
    drs_rule: MUST
iaas-configurations:
- datacenter: ((vsphere_datacenter))
  disk_type: thin
  enable_human_readable_name: true
  ephemeral_datastores_string: ((vsphere_datastore))
  name: default
  nsx_address: ((nsx_address))
  nsx_ca_certificate: ((nsx_ca_certificate))
  nsx_mode: nsx-t
  nsx_networking_enabled: true
  nsx_password: ((nsx_password))
  nsx_t_auth_type: local_user
  nsx_t_tag_nsx_vm_objects: true
  nsx_t_use_policy_api: true
  nsx_username: ((nsx_username))
  persistent_datastores_string: ((vsphere_datastore))
  ssl_verification_enabled: false
  vcenter_host: ((vcenter_url))
  vcenter_password: ((vcenter_password))
  vcenter_username: ((vcenter_username))
network-assignment:
  network:
    name: cp
  singleton_availability_zone:
    name: az1
networks-configuration:
  icmp_checks_enabled: true
  networks:
  - name: cp
    subnets:
    - iaas_identifier: ((control_plane_net))
      cidr: ((control_plane_net_cidr))
      dns: ((dns))
      gateway: ((control_plane_net_gateway))
      reserved_ip_ranges: ((control_plane_net_reserved))
      availability_zone_names:
      - az1
properties-configuration:
  director_configuration:
    ntp_servers_string: ((ntp))
  security_configuration:
    opsmanager_root_ca_trusted_certs: true
vmextensions-configuration:
  - name: concourse-lb
    cloud_properties:
      nsxt:
        ns_groups:
        - cp_web
  - name: increased-disk
    cloud_properties:
      disk: 102400